### ISSUE TITLE
Bind requirements to specific versions

### ISSUE THREAD

**Issue by miterion** [d120/djangocms#17]
Most of our django projects have fixed requirement bindings, which get regularly updatet by the dependabot. It would make sense to do this here too, since it simplifies upgrading the CMS.

**Comment by joachimschmidt557** [comment]
Ok, I can look into pinning some versions.

**Comment by joachimschmidt557** [comment]
@miterion Should I run `pip freeze` or would that be too much? I can also manually pin the depenencies which are in `requirements.txt` at the moment.

**Comment by miterion** [comment]
I think it would be best to only pin the dependencies in the requirements file. Else there will be lots of notifications if any of the sub dependencies needs is updated.

**Comment by joachimschmidt557** [comment]
Implemented in a35edc12750fd27adb3619653e958fd1ed02a624
