### ISSUE TITLE
Move from typeface to fontsource

### ISSUE THREAD

**Issue by joachimschmidt557** [d120/djangocms#35]
According to the README of https://github.com/KyleAMathews/typefaces, typefaces is deprecated in favour of https://github.com/fontsource/fontsource.

I suggest we switch to https://www.npmjs.com/package/fontsource-libre-franklin and fix anything that broke.

**Comment by Xiphoseer** [comment]
Sounds good, do you want to prepare a PR for that?

**Comment by joachimschmidt557** [comment]
Yes, I'll do that.

**Comment by Xiphoseer** [comment]
Closed by #42
