### ISSUE TITLE
--process-dependency-links is not available in pip anymore

### ISSUE THREAD

**Issue by miterion** [d120/djangocms#8]
Since this is only necessary for pyTUID, it should be fixed with https://github.com/d120/pyTUID/issues/21

**Comment by joachimschmidt557** [comment]
As the referenced issue has been fixed, can the `--process-dependency-links` flag be removed?

**Comment by miterion** [comment]
Sure

**Comment by joachimschmidt557** [comment]
Ok. As far as I can see, the only dependecy in `requirements.txt` that needs `pyTUID` is pyBuchaktion, where we would need to update that there if we want to keep pyBuchaktion.

**Comment by miterion** [comment]
In that case I would seriously evaluate removing pybuchaktion.

**Comment by Xiphoseer** [comment]
Yes, I would remove pyTUID and pyBuchaktion from the website. They're currently unused, the only project we ever published as a plugin to the CMS and by now I don't think it was a good choice to include it anyways.

In [#9](https://github.com/d120/djangocms/pull/9/files#diff-1c185a007ef577542f77b008190184b2R84-R85) they are already commented out.

**Comment by miterion** [comment]
Since the dependencies are removed now on the main branch I  will close the issue
